fn abc() {
    a = Exception()
    a = a.try + 2

    return a
}

b = abc()

println(b)