try {
    for i in 0..3000000 {
        Exception()
    }
} catch {
    println("An error occurred during the loop execution.")
}
